Spotify Integration
WPI-LNL/lnldb pull request #637
Opened 2022-04-17 01:37 UTC by tnurse18

This takes the old temporary Wall of Sound features and turns them into a more robust solution for working with LNL's Spotify accounts.

- Collect song requests for events
- Send requests to a Spotify queue and control playback

2022-04-17 18:46 UTC, benjamin-antupit commented on spotify/api.py
> +    """ Custom Spotipy cache handler. Saves authentication information to the database. """
```suggestion
    """ Custom Spotify cache handler. Saves authentication information to the database. """
```

2022-04-18 23:04 UTC, tnurse18 commented on spotify/tests.py
> +        # Check that approval permissions are required
```suggestion
        # Check required permissions
```

2022-04-20 19:40 UTC, Muirrum reviewed
Overall this looks good to me, I'll test it locally first.

2022-04-24 04:46 UTC, Muirrum requested changes
There are some cosmetic issues on the song request page that look like a lack of a `main.css` file.
![screenshot-2022-04-24-004309](https://user-images.githubusercontent.com/8702646/164957050-5f6c9f00-1afa-4e94-8e6c-4a05c98588de.png)

Other than that, it functionally works flawlessly. Thank you so much for this!

2022-04-24 04:52 UTC, Muirrum commented on site_tmpl/song_requests.html
> +{% extends 'base_admin.html' %}
If at all possible, it would be nice to add a `<meta http-equiv="refresh" content="30"/>` or something, to keep the list of song requests current.

2022-04-24 18:36 UTC, Muirrum approved these changes
Turns out, this relies on the static site's `main.css`. Everything LGTM

2022-04-24 18:36 UTC, merged